# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings 下面是用在footer里面为了找工作的几个陈述，可以修改 
# 事实证明主页没有变 需要修改 index
title-bold: QUERY
title-normal: QUERY THINGS AROUND {...}
email: helloworld.zoey@gmail.com
description: a twenty-something-year-old girl having a hard time introducing herself
baseurl: '' # the subpath of your site, e.g. /blog
url: "https://naliece.github.io" # the base hostname & protocol for your site
author: Qiaoye 'QUERY' Zou
phone: +86 15061790616
languages: Python
skills: System development, Production engineering (DevOps), Ruby on Rails
rates: Discounted rates for OpenSource
workplace: Available worldwide

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings 直接写social media 的 url 也是 footer 的 link
500px_url:
facebook_url:
github_url: 
gitlab_url:
googleplus_url:
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
